import React from 'react';

function Menu3() {

    return (
        <div className='app-container' >
            <div className='app-container1'>

                <h3>基本料金</h3>
                ・介護保険からの給付サービスを利用する場合は,原則として基本料金（下記料金表）の１割です。ただし、介護保険の給付の範囲を越えたサービス利用は全額自己負担となります。<br></br>


                <h2>居宅介護利用料金表(利用者負担額)</h2>
                <table className='empty-hide'>
                    <tr>
                        <th>身体介護 &<br></br>通院等介助（身体介護を伴う）
                        </th>
                        <td>早朝・夜間</td>
                        <td>昼間</td>
                        <td>深夜</td>
                    </tr>
                    <tr>
                        <td>30分未満</td>
                        <td>342円</td>
                        <td>273円</td>
                        <td>410円</td>
                    </tr>
                    <tr>
                        <td>30分以上1時間未満</td>
                        <td>539円</td>
                        <td>431円</td>
                        <td>647円</td>
                    </tr>
                    <tr>
                        <td>1時間以上1時間30分未満</td>
                        <td>783円</td>
                        <td>626円</td>
                        <td>939円</td>
                    </tr>
                    <tr>
                        <td>1時間30分以上2時間未満</td>
                        <td>894円</td>
                        <td>715円</td>
                        <td>1072円</td>
                    </tr>
                    <tr>
                        <td>2時間以上2時間30分未満</td>
                        <td>1006円</td>
                        <td>805円</td>
                        <td>1207円</td>
                    </tr>
                    <tr>
                        <td>2時間30分以上3時間未満</td>
                        <td>1117円</td>
                        <td>894円</td>
                        <td>1340円</td>
                    </tr>
                    <tr>
                        <td>3時間以上3時間30分未満</td>
                        <td>1228円</td>
                        <td>983円</td>
                        <td>1474円</td>
                    </tr>
                    <tr>
                        <td>3時間以上30分を増やすごとに</td>
                        <td>111円</td>
                        <td>89円</td>
                        <td>134円</td>
                    </tr>
                    <tr>
                        <th>家事援助</th>
                        <td>早朝・夜間</td>
                        <td>昼間</td>
                        <td>深夜</td>
                    </tr>
                    <tr>
                        <td>30分未満</td>
                        <td>140円</td>
                        <td>112円</td>
                        <td>168円</td>
                    </tr>
                    <tr>
                        <td>30分以上45分未満</td>
                        <td>203円</td>
                        <td>163円</td>
                        <td>244円</td>
                    </tr>
                    <tr>
                        <td>45分以上1時間未満</td>
                        <td>262円</td>
                        <td>210円</td>
                        <td>126円</td>
                    </tr>
                    <tr>
                        <td>1時間以上1時間15分未満</td>
                        <td>318円</td>
                        <td>255円</td>
                        <td>382円</td>
                    </tr>
                    <tr>
                        <td>1時間15分以上1時間30分未満</td>
                        <td>368円</td>
                        <td>294円</td>
                        <td>441円</td>
                    </tr>
                    <tr>
                        <td>1時間30分以上1時間45分未満</td>
                        <td>414円</td>
                        <td>331円</td>
                        <td>497円</td>
                    </tr>
                    <tr>
                        <td>1時間45分以上15分を増すごとに</td>
                        <td>47円</td>
                        <td>38円</td>
                        <td>40円</td>
                    </tr>
                    <tr>
                        <th>通院等介助(身体介護を伴わない)</th>
                        <td>早朝・夜間</td>
                        <td>昼間</td>
                        <td>深夜</td>
                    </tr>
                    <tr>
                        <td>30分未満</td>
                        <td>140円</td>
                        <td>273円</td>
                        <td>168円</td>
                    </tr>
                    <tr>
                        <td>30分以上1時間未満</td>
                        <td>153円</td>
                        <td>431円</td>
                        <td>220円</td>
                    </tr>
                    <tr>
                        <td>1時間以上1時間30分未満</td>
                        <td>368円</td>
                        <td>626円</td>
                        <td>441円</td>
                    </tr>
                    <tr>
                        <td>1時間30分以上2時間未満</td>
                        <td>461円</td>
                        <td>715円</td>
                        <td>553円</td>
                    </tr>
                    <tr>
                        <td>3時間以上30分を増すごとに</td>
                        <td>111円</td>
                        <td>89円</td>
                        <td>134円</td>
                    </tr>
                </table>
                <h2>同行援護利用料金表(利用者負担額)</h2>
                <table className='empty-hide'>
                    <tr>
                        <th>同行援護</th>
                        <td>早朝・夜間</td>
                        <td>昼間</td>
                        <td>深夜 </td>
                    </tr>
                    <tr>
                        <td>30分未満</td>
                        <td>207円</td>
                        <td>202円</td>
                        <td>212円</td>
                    </tr>
                    <tr>
                        <td>30分以上1時間未満</td>
                        <td>400円</td>
                        <td>320円</td>
                        <td>480円</td>
                    </tr>
                    <tr>
                        <td>1時間以上1時間30分未満</td>
                        <td>577円</td>
                        <td>462円</td>
                        <td>693円</td>
                    </tr>
                    <tr>
                        <td>1時間30分以上2時間未満</td>
                        <td>665円</td>
                        <td>532円</td>
                        <td>798円</td>
                    </tr>
                    <tr>
                        <td>2時間以上2時間30分未満</td>
                        <td>747円</td>
                        <td>601円</td>
                        <td>901円</td>
                    </tr>
                    <tr>
                        <td>2時間30分以上3時間未満</td>
                        <td>838円</td>
                        <td>670円</td>
                        <td>1005円</td>
                    </tr>
                    <tr>
                        <td>3時間以上3時間30分未満</td>
                        <td>924円</td>
                        <td>739円</td>
                        <td>1109円</td>
                    </tr>
                    <tr>
                        <td>3時間以上30分を増すごとに</td>
                        <td>87円</td>
                        <td>70円</td>
                        <td>104円</td>
                    </tr>
                </table>

                <h2>重度訪問介護利用料金表(利用者負担額)</h2>
                <table className='empty-hide'>
                    <tr>
                        <th>重度訪問介護&
                            入院・入所</th>
                        <td>早朝・夜間</td>
                        <td>昼間</td>
                        <td>深夜 </td>
                    </tr>
                    <tr>
                        <td>１時間未満</td>
                        <td>253円</td>
                        <td>202円</td>
                        <td>303円</td>
                    </tr>
                    <tr>
                        <td>1時間以上1時間30分未満</td>
                        <td>376円</td>
                        <td>301円</td>
                        <td>451円</td>
                    </tr>
                    <tr>
                        <td>1時間30分以上2時間未満</td>
                        <td>502円</td>
                        <td>402円</td>
                        <td>602円</td>
                    </tr>
                    <tr>
                        <td>2時間以上2時間30分未満</td>
                        <td>627円</td>
                        <td>501円</td>
                        <td>752円</td>
                    </tr>
                    <tr>
                        <td>2時間30分以上3時間未満</td>
                        <td>753円</td>
                        <td>602円</td>
                        <td>903円</td>
                    </tr>
                    <tr>
                        <td>3時間以上3時間30分未満</td>
                        <td>876円</td>
                        <td>701円</td>
                        <td>1051円</td>
                    </tr>
                    <tr>
                        <td>3時間以上4時間未満</td>
                        <td>1002円</td>
                        <td>802円</td>
                        <td>1202円</td>
                    </tr>

                    <tr>
                        <th>移動介護加算</th>
                        <td>早朝・夜間</td>
                        <td>昼間</td>
                        <td>深夜 </td>
                    </tr>
                    <tr>
                        <td>1時間未満</td>
                        <td>138円</td>
                        <td>110円</td>
                        <td>165円</td>
                    </tr>
                    <tr>
                        <td>1時間以上1時間30分未満</td>
                        <td>172円</td>
                        <td>138円</td>
                        <td>233円</td>
                    </tr>
                    <tr>
                        <td>1時間30分以上2時間未満</td>
                        <td>206円</td>
                        <td>165円</td>
                        <td>247円</td>
                    </tr>
                    <tr>
                        <td>2時間以上2時間30分未満</td>
                        <td>240円</td>
                        <td>192円</td>
                        <td>288円</td>
                    </tr>
                    <tr>
                        <td>2時間30分以上3時間未満</td>
                        <td>275円</td>
                        <td>220円</td>
                        <td>329円</td>
                    </tr>

                    <tr>
                        <td>3時間以上</td>
                        <td>343円</td>
                        <td>275円</td>
                        <td>412円</td>
                    </tr>

                </table>
                <p className='font12'>
                    ※表示料金は利用者が負担する料金（一割）です。<br></br>
                    &nbsp;&nbsp;&nbsp;1単位=10円で算出した概算料金です。<br></br>
                    &nbsp;&nbsp;&nbsp;正確な料金はお問い合わせください。
                </p>
            </div>
        </div>


    );
}

export default Menu3;